import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="p-10">Nikhil Abraham</h1>
    </div>
  );
}
